version: '3'
services:
  backend-service:
    image: ghcr.io/cybermouflons/ccsc2025/popcorn-backend-service:latest
    restart: always
    build: ./setup/backend-service/
    environment:
      - flag=ECSC{L1gHtS_C4meRa_D3c3pTi0n...I_Me4N_AC7ioN}
    networks:
      appnet:
    depends_on:
      - cache-service
  cache-service:
    image: ghcr.io/cybermouflons/ccsc2025/popcorn-cache-service:latest
    restart: always
    build: ./setup/cache-service/
    ports:
      - 3000:80
    networks:
      appnet:
        aliases:
          - web-app
  admin-bot:
    image: ghcr.io/cybermouflons/ccsc2025/popcorn-admin-bot:latest
    restart: always
    build: ./setup/admin-bot/
    depends_on:
      - cache-service
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=F6vF0Q3OXZbK5QZOSBlDzGU1LTn6ieol
      - BASE_URL=http://web-app
    networks:
      appnet:

networks:
  appnet: