version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2025/log-recorder:latest
    restart: always
    ports:
      - 4242:4242
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: log-recorder