version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2025/zer0cool:latest
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels: 
        ctf.challenge.name: zer0cool