version: '3.8'

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2025/date-mcp:latest
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./setup
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: date-mcp
