version: "3.7"

services:
  challenge:
    image: ghcr.io/cybermouflons/ccsc2025/this-is-different:latest
    restart: always
    ports:
      - 1337:1337
    build:
      context: ./src
      dockerfile: Dockerfile
      labels:
        ctf.challenge.name: this-is-different